---
- name: Install OpenShift 3.9
  hosts: all
  gather_facts: False
  remote_user: cloud-user
  vars:
    control_machine: localhost
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    domain: bcbssc-cds.com
    version: 3.9
  roles:
    # provision volumes 
    # - { role: provision }

    # create and add DNS entries
    - { role: dns}

    # # create and copy SSH keys
    - { role: keys }    

    # # register with subscription manager
    # - { role: rhn }

    # # prepare all hosts for installation
    - { role: prepare } 

    # # let it rip!
    - { role: install }
