# ---
- name: Create DNS record 
  ipa_dnsrecord:
    ipa_host: "{{ ipa_server }}"
    ipa_pass: "{{ ipa_pass }}"
    state: present
    zone_name: "{{ domain }}"
    record_name: "{{ inventory_hostname }}"
    record_type: "A"
    record_value: "{{ ansible_default_ipv4.address }}"
    validate_certs: False
  delegate_to: "{{ control_machine }}"

# - name: Create DNS record for apps subdomain
  ipa_dnsrecord:
    ipa_host: "{{ ipa_server }}"
    ipa_pass: "{{ ipa_pass }}"
    state: present
    zone_name: "{{ domain }}"
    record_name: "*.apps"
    record_type: "A"
    record_value: "{{ ansible_default_ipv4.address }}"
    validate_certs: False
  delegate_to: "{{ control_machine }}"
  when: inventory_hostname == groups['masters'][0]

# - name: Add the host
  ipa_host:
    name: "{{ inventory_hostname }}.{{ domain }}"
    state: present
    ipa_host: "{{ ipa_server }}"
    ipa_pass: "{{ ipa_pass }}"
    validate_certs: False
  delegate_to: "{{ control_machine }}"

- name: Copy dhclient.conf
  become: True
  template:
    src: dhclient.conf.j2
    dest: /etc/dhcp/dhclient.conf

- name: Insert DNS search order into network config
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: '^SEARCH='
    line: "SEARCH={{ domain }}"
    
- name: Set hostname
  become: true
  hostname:
    name: "{{ inventory_hostname }}.{{ domain }}" 

- name: Restart network service
  become: True
  service:
    name: network
    state: restarted      
